version: '3'
services:
  receive-data:
    build:
      context: ./
      dockerfile: Dockerfile.receive
    image: receive-data
    ports:
     - "5000:5000"
   
    volumes:
      - ./config/:/usr/src/app/config
      - ./received/:/usr/src/app/received
  send-data:
    build:
      context: ./
      dockerfile: Dockerfile.send
    image: send-data
    depends_on:
      - receive-data
    network_mode: "host"
    volumes:
      - ./config/:/usr/src/app/config
      - ./input/:/usr/src/app/input


